// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_football_test/test/winner_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:flutter_football_test/repository/football_data_repository.dart'
    as _i6;
import 'package:flutter_football_test/repository/models/match.dart' as _i5;
import 'package:flutter_football_test/repository/models/matches.dart' as _i3;
import 'package:flutter_football_test/repository/models/team.dart' as _i4;
import 'package:flutter_football_test/repository/service/football_data_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeFootballDataService_0 extends _i1.Fake
    implements _i2.FootballDataService {}

class _FakeFbMatches_1 extends _i1.Fake implements _i3.FbMatches {}

class _FakeTeam_2 extends _i1.Fake implements _i4.Team {}

/// A class which mocks [FbMatches].
///
/// See the documentation for Mockito's code generation for more information.
class MockFbMatches extends _i1.Mock implements _i3.FbMatches {
  MockFbMatches() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.FbMatch> get matches =>
      (super.noSuchMethod(Invocation.getter(#matches),
          returnValue: <_i5.FbMatch>[]) as List<_i5.FbMatch>);
}

/// A class which mocks [Team].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeam extends _i1.Mock implements _i4.Team {
  MockTeam() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
}

/// A class which mocks [FootballDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFootballDataRepository extends _i1.Mock
    implements _i6.FootballDataRepository {
  MockFootballDataRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FootballDataService get service => (super.noSuchMethod(
      Invocation.getter(#service),
      returnValue: _FakeFootballDataService_0()) as _i2.FootballDataService);
  @override
  _i7.Future<_i3.FbMatches> getMatches() =>
      (super.noSuchMethod(Invocation.method(#getMatches, []),
              returnValue: Future<_i3.FbMatches>.value(_FakeFbMatches_1()))
          as _i7.Future<_i3.FbMatches>);
  @override
  _i7.Future<_i4.Team> getTeam(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTeam, [id]),
              returnValue: Future<_i4.Team>.value(_FakeTeam_2()))
          as _i7.Future<_i4.Team>);
}
